- name: start proxy
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: kube-proxy
- name: restart proxy
  systemd:
    state: restarted
    daemon_reload: yes
    name: kube-proxy