- copy:
    src: "{{ role_path }}/files/default.yaml"
    dest: /tmp
    owner: root
    group: root
    mode: 0644
- name: Deploy Default StorageClass
  command: kubectl apply -f /tmp/default.yaml
  ignore_errors: yes