- name: start apiserver
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: kube-apiserver
- name: restart apiserver
  systemd:
    state: restarted
    daemon_reload: yes
    name: kube-apiserver