# CHECK WORKER AND INSTALL ADDONS
- name: Check nodes
  hosts: master-1
  become: true
  become_method: sudo
  tasks:
    - name: Check registered nodes
      command: kubectl get nodes -o wide
      register: kubenodes
    - debug: var=kubenodes.stdout_lines
    - copy:
        src: ../../addons/kube-dashboard.yaml
        dest: /
        owner: root
        group: root
        mode: 0644
    - copy:
        src: ../../addons/kubedns.yaml
        dest: /
        owner: root
        group: root
        mode: 0644
    - name: Deploy addons dns
      command: kubectl apply -f /kubedns.yaml
      ignore_errors: yes
    - name: Deploy addons dashboard
      command: kubectl apply -f /kube-dashboard.yaml
      ignore_errors: yes