kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard