- include: check.yml
- include: install_apiserver.yml
- include: install_kubectl.yml

- template:
    src: "{{ role_path }}/templates/token.csv.j2"
    dest: /var/lib/kubernetes/token.csv
    owner: root
    group: root
    mode: 0644
- copy:
    src: "{{ role_path }}/files/authorization-policy.jsonl"
    dest: /var/lib/kubernetes/
    owner: root
    group: root
    mode: 0644
- copy:
    src: "{{ role_path }}/files/gce.conf"
    dest: /var/lib/kubernetes/
    owner: root
    group: root
    mode: 0644

- name: set fact etcd ip
  set_fact: etcd_item="https://{{ item }}:2379"
  with_items: "{{ etcd_ips }}"
  register: etcd_result

- name: Set fact for template
  set_fact: etcd_servers_ip="{{ etcd_result.results | map(attribute='ansible_facts.etcd_item') | join(',') }}"

- name: Creates file apiserver service
  template:
        src: "{{ role_path }}/templates/kube-apiserver.service.j2"
        dest: /etc/systemd/system/kube-apiserver.service
        owner: root
        group: root
        mode: 0644
  notify:
  - start apiserver
  - restart apiserver