- name: Download kube-scheduler binary
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.6.4/bin/linux/amd64/kube-scheduler
    dest: /usr/bin/kube-scheduler

- name: Changing kube-scheduler permission
  file: dest=/usr/bin/kube-scheduler mode=a+x