- include: check.yml
- include: install_scheduler.yml

- name: Creates file scheduler service
  template:
        src: "{{ role_path }}/templates/kube-scheduler.service.j2"
        dest: /etc/systemd/system/kube-scheduler.service
        owner: root
        group: root
        mode: 0644
  notify:
  - start scheduler
  - restart scheduler