# Example Playbook
- name: Compute Engine Instance Examples
  hosts: localhost
  gather_facts: False
  connection: local
  vars:
    service_account_email: "44821912319-compute@developer.gserviceaccount.com"
    credentials_file: "/home/pendi/svc_account/intern-kevin-e22183b42802.json"
    project_id: "intern-kevin"
  tasks:
    - name: Create Custom Network
      gce_net:
        name: ansikubernetes
        mode: custom
        subnet_name: "ansikube"
        subnet_region: asia-northeast1
        ipv4_range: '10.240.16.0/24'
        state: "present"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"

    - name: Create Firewall Rule
      gce_net:
        name: ansikubernetes
        fwname: "ansi-allow"
        allowed: "tcp;udp;icmp"
        state: "present"
        src_range: ['0.0.0.0/0']
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"

    - name: Create instances
      gce:
        instance_names: "etc1,etc2,master1,master2,slave1,slave2"
        zone: asia-northeast1-a
        machine_type: n1-standard-1
        image: ubuntu-1504-vivid
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        ip_forward: true
        network : ansikubernetes
        subnetwork : ansikube
      register: gce