#NODES
- name: Configure nodes
  hosts: node
  become: true
  become_method: sudo
  tasks:
    - name: Creates directory /var/lib/kubernetes
      file: path=/var/lib/kubernetes state=directory
    - name: Move certs to /var/lib/kubernetes
      command: mv /ca.pem /kubernetes-key.pem /kubernetes.pem /var/lib/kubernetes/
    - name: Download Docker binary
      get_url:
        url: https://get.docker.com/builds/Linux/x86_64/docker-1.11.2.tgz
        dest: /docker-1.11.2.tgz
    - unarchive:
        src: /docker-1.11.2.tgz
        dest: /
        remote_src: True
    - name: Copy extracted files to /usr/bin
      copy: src=/docker/docker dest=/usr/bin/ remote_src=yes directory_mode=yes
    - name: Copy extracted files to /usr/bin
      copy: src=/docker/docker-containerd dest=/usr/bin/ remote_src=yes directory_mode=yes
    - name: Copy extracted files to /usr/bin
      copy: src=/docker/docker-containerd-ctr dest=/usr/bin/ remote_src=yes directory_mode=yes
    - name: Copy extracted files to /usr/bin
      copy: src=/docker/docker-containerd-shim dest=/usr/bin/ remote_src=yes directory_mode=yes
    - name: Copy extracted files to /usr/bin
      copy: src=/docker/docker-runc dest=/usr/bin/ remote_src=yes directory_mode=yes
    - name: Creates directory /opt/cni
      file: path=/opt/cni state=directory
    - name: Download CNI plugin
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/network-plugins/cni-c864f0e1ea73719b8f4582402b0847064f9883b0.tar.gz
        dest: /cni-c864f0e1ea73719b8f4582402b0847064f9883b0.tar.gz
    - unarchive:
        src: /cni-c864f0e1ea73719b8f4582402b0847064f9883b0.tar.gz
        dest: /opt/cni
        remote_src: True

    - name: Download kubelet binary
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.6.4/bin/linux/amd64/kubelet
        dest: /usr/bin/kubelet
    - name: Download kube-proxy binary
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.6.4/bin/linux/amd64/kube-proxy
        dest: /usr/bin/kube-proxy
    - name: Download kubectl binary
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.6.4/bin/linux/amd64/kubectl
        dest: /usr/bin/kubectl

    - name: Changing kubelet permission
      file: dest=/usr/bin/kubelet mode=a+x

    - name: Changing kube-proxy permission
      file: dest=/usr/bin/kube-proxy mode=a+x

    - name: Changing kubectl permission
      file: dest=/usr/bin/kubectl mode=a+x

    - copy:
        src: templates/systemd/kubelet.service
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: 0644
    - copy:
        src: templates/systemd/kube-proxy.service
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: 0644
    - copy:
        src: templates/systemd/docker.service
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: 0644
    - name: Reload systemctl
      command: systemctl daemon-reload
    - name: Enable docker
      command: systemctl enable docker
    - name: Start dockerservice
      command: systemctl start docker
    - name: Restart docker service
      command: systemctl restart docker
    - name: Enable kubelet
      command: systemctl enable kubelet
    - name: Start kubelet service
      command: systemctl start kubelet
    - name: Restart kubelet service
      command: systemctl restart kubelet
    - name: Enable kube-proxy
      command: systemctl enable kube-proxy
    - name: Start kube-proxy service
      command: systemctl start kube-proxy
    - name: Restart kube-proxy service
      command: systemctl restart kube-proxy