# ETCD
- name: Configure etcd cluster
  hosts: etcd
  become: true
  become_method: sudo
  tasks:
    - name: Creates directory /etc/etcd
      file: path=/etc/etcd state=directory
    - name: Move certs to /etc/etcd
      command: mv /ca.pem /kubernetes-key.pem /kubernetes.pem /etc/etcd/
    - name: Download etcd binary
      get_url:
        url: https://github.com/coreos/etcd/releases/download/v3.1.8/etcd-v3.1.8-linux-amd64.tar.gz
        dest: /etcd-v3.1.8-linux-amd64.tar.gz
    - unarchive:
        src: /etcd-v3.1.8-linux-amd64.tar.gz
        dest: /
        remote_src: True
    - name: Copy extracted files to /usr/bin
      copy: src=/etcd-v3.1.8-linux-amd64/etcd dest=/usr/bin/ remote_src=yes directory_mode=yes
    - name: Copy extracted files to /usr/bin
      copy: src=/etcd-v3.1.8-linux-amd64/etcdctl dest=/usr/bin/ remote_src=yes directory_mode=yes
    - name: Changing permission
      file: dest=/usr/bin/etcd mode=a+x
    - name: Changing permission
      file: dest=/usr/bin/etcdctl mode=a+x
    - name: Creates directory /var/lib/etcd
      file: path=/var/lib/etcd state=directory
    - copy:
        src: templates/systemd/etcd.service
        dest: /
        owner: root
        group: root
        mode: 0644
    - replace:
        path: /etcd.service
        regexp: 'INTERNAL_IP'
        replace: "{{ ansible_eth0.ipv4.address }}"
    - replace:
        path: /etcd.service
        regexp: 'ETCDNAME'
        replace: "{{ inventory_hostname }}"
    - name: Move etcd service
      command: mv /etcd.service /etc/systemd/system/
    - name: Reload systemctl
      command: systemctl daemon-reload
    - name: Enable etcd
      command: systemctl enable etcd
    - name: Start etcd service
      command: systemctl start etcd
    - name: Restart etcd service
      command: systemctl restart etcd
    - name: Check etcd cluster
      command: etcdctl --ca-file=/etc/etcd/ca.pem cluster-health
      register: etc
    - debug: var=etc.stdout_lines