- name: Download etcd binary
  get_url:
    url: https://github.com/coreos/etcd/releases/download/v3.1.8/etcd-v3.1.8-linux-amd64.tar.gz
    dest: /tmp/etcd-v3.1.8-linux-amd64.tar.gz
- unarchive:
    src: /tmp/etcd-v3.1.8-linux-amd64.tar.gz
    dest: /tmp/
    remote_src: True
- name: Copy extracted files to /usr/bin
  copy: src=/tmp/etcd-v3.1.8-linux-amd64/etcd dest=/usr/bin/ remote_src=yes directory_mode=yes
- name: Copy extracted files to /usr/bin
  copy: src=/tmp/etcd-v3.1.8-linux-amd64/etcdctl dest=/usr/bin/ remote_src=yes directory_mode=yes
- name: Changing permission
  file: dest=/usr/bin/etcd mode=a+x
- name: Changing permission
  file: dest=/usr/bin/etcdctl mode=a+x