- copy:
    src: "{{ role_path }}/files/default-backend.yaml"
    dest: /tmp
    owner: root
    group: root
    mode: 0644
- copy:
    src: "{{ role_path }}/files/nginx-ingress-controller.yaml"
    dest: /tmp
    owner: root
    group: root
    mode: 0644
- copy:
    src: "{{ role_path }}/files/system.yaml"
    dest: /tmp
    owner: root
    group: root
    mode: 0644
- name: Deploy backend
  command: kubectl apply -f /tmp/default-backend.yaml
  ignore_errors: yes
- name: Label node-1
  command: kubectl label node node-1 ingress=nginx
  ignore_errors: yes
- name: Deploy Ingress Controller to node-1
  command: kubectl apply -f /tmp/nginx-ingress-controller.yaml
  ignore_errors: yes
- name: Deploy Ingress rule
  command: kubectl apply -f /tmp/system.yaml
  ignore_errors: yes