- include: check.yml
- include: install_controller.yml

- copy:
    src: "{{ role_path }}/files/gce.conf"
    dest: /var/lib/kubernetes/
    owner: root
    group: root
    mode: 0644
- copy:
    src: "{{ role_path }}/files/kubeconfig"
    dest: /var/lib/kubernetes/
    owner: root
    group: root
    mode: 0644

- name: Copy file controller service
  copy:
        src: "{{ role_path }}/files/kube-controller-manager.service"
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: 0644
  notify:
  - start controller
  - restart controller