- include: check.yml
- include: install_flannel.yml

- name: set fact etcd ip
  set_fact: etcd_item="https://{{ item }}:2379"
  with_items: "{{ etcd_ips }}"
  register: etcd_result

- name: Set fact for template
  set_fact: etcd_servers_ip="{{ etcd_result.results | map(attribute='ansible_facts.etcd_item') | join(',') }}"

- name: Create file flannelservice from template
  template:
        src: "{{ role_path }}/templates/flannel.service.j2"
        dest: /etc/systemd/system/flannel.service
        owner: root
        group: root
        mode: 0644
  notify:
  - start flannel
  - restart flannel
