apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: jenkins-home
  namespace: jenkins
  labels:
    user: jenkins
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "jenkins-home"