- name: Download kubelet binary
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.6.4/bin/linux/amd64/kubelet
    dest: /usr/bin/kubelet

- name: Changing kubelet permission
  file: dest=/usr/bin/kubelet mode=a+x