- include: check.yml
- include: install_kubelet.yml

- name: Creates file kubeconfig
  template:
        src: "{{ role_path }}/templates/kubeconfig.j2"
        dest: /var/lib/kubelet/kubeconfig
        owner: root
        group: root
        mode: 0644

- copy:
    src: "{{ role_path }}/files/gce.conf"
    dest: /var/lib/kubernetes/
    owner: root
    group: root
    mode: 0644

- name: set fact master ip for templates
  set_fact: master_item="https://{{ item }}:6443"
  with_items: "{{ master_ips }}"
  register: master_result
- name: make a list for templates
  set_fact: master_ip_list="{{ master_result.results | map(attribute='ansible_facts.master_item') | join(',') }}"

- name: Creates file kubelet service
  template:
        src: "{{ role_path }}/templates/kubelet.service.j2"
        dest: /etc/systemd/system/kubelet.service
        owner: root
        group: root
        mode: 0644
  notify:
  - start kubelet
  - restart kubelet