apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: update-hpa
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-hpa
            image: wernight/kubectl
            command: ["/bin/sh"]
            args: ["-c", "kubectl delete hpa php-apache && kubectl autoscale deployment php-apache --min=3 --max=50 --cpu-percent=50"]
          restartPolicy: OnFailure