apiVersion: v1
kind: Pod
metadata:
  name: kubectl
  namespace: default
spec:
  containers:
  - image: wernight/kubectl
    imagePullPolicy: IfNotPresent
    name: kubectl
    command:
      - sleep
      - "3600"
  restartPolicy: Always