- name: start docker
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: docker
- name: restart docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker