- copy:
    src: "{{ role_path }}/files/es-service.yaml"
    dest: /tmp
    owner: root
    group: root
    mode: 0644
- copy:
    src: "{{ role_path }}/files/es-controller.yaml"
    dest: /tmp
    owner: root
    group: root
    mode: 0644
- copy:
    src: "{{ role_path }}/files/kibana-service.yaml"
    dest: /tmp
    owner: root
    group: root
    mode: 0644
- copy:
    src: "{{ role_path }}/files/fluentd-daemonset-elasticsearch.yaml"
    dest: /tmp
    owner: root
    group: root
    mode: 0644
- copy:
    src: "{{ role_path }}/files/kibana-controller.yaml"
    dest: /tmp
    owner: root
    group: root
    mode: 0644
- name: Deploy elasticsearch service
  command: kubectl apply -f /tmp/es-service.yaml
  ignore_errors: yes
- name: Deploy kibana service
  command: kubectl apply -f /tmp/kibana-service.yaml
  ignore_errors: yes
- name: Deploy fluentd ds
  command: kubectl apply -f /tmp/fluentd-daemonset-elasticsearch.yaml
  ignore_errors: yes
- name: Deploy elasticsearch controller
  command: kubectl apply -f /tmp/es-controller.yaml
  ignore_errors: yes
- name: Deploy kibana controller
  command: kubectl apply -f /tmp/kibana-controller.yaml
  ignore_errors: yes