- name: start kubelet
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: kubelet
- name: restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet