- name: Stop docker service
  command: systemctl stop docker
  ignore_errors: yes
- name: Delete docker bridge
  command: iptables -t nat -F
  ignore_errors: yes
- name: Delete docker bridge
  command: ip link set docker0 down
  ignore_errors: yes
- name: Delete docker bridge
  command: ip link delete docker0
  ignore_errors: yes
- name: Delete cbr0 bridge
  command: ip link set cbr0 down
  ignore_errors: yes
- name: Delete cbr0 bridge
  command: ip link delete cbr0
  ignore_errors: yes
- name: Create cbr0 bridge
  command: ip link add name cbr0 type bridge
- name: Create cbr0 bridge
  command: ip link set dev cbr0 mtu 1460
- name: Create cbr0 bridge
  command: "ip addr add 10.200.{{ inventory_hostname[-1] | int - 1}}.1/24 dev cbr0"
- debug:
    msg: "{{ inventory_hostname[-1] | int - 1}}"
- name: Create cbr0 bridge
  command: ip link set dev cbr0 up
  notify:
  - start docker
  - restart docker