- include: check.yml
- include: install_docker.yml
- include: install_cni.yml
- include: bridge.yml

- name: Copy file docker service
  copy:
        src: "{{ role_path }}/files/docker.service"
        dest: /etc/systemd/system/docker.service
        owner: root
        group: root
        mode: 0644
  notify:
  - start docker
  - restart docker
