- hosts: etcd
  become: true
  become_method: sudo
  roles:
    - etcd
  tasks:
    - meta: flush_handlers
    - name: Check etcd cluster
      command: etcdctl --ca-file=/etc/etcd/ca.pem --cert-file=/etc/etcd/kubernetes.pem --key-file=/etc/etcd/kubernetes-key.pem cluster-health 
      register: etc
    - debug: var=etc.stdout_lines