- name: Create certificate
  hosts: localhost
  connection: local
  roles:
     - certs

- name: Copy certificate to all
  hosts: master,etcd,node
  become: true
  become_method: sudo
  tasks:
    - copy:
        src: roles/certs/files/ca.pem
        dest: /tmp
        owner: root
        group: root
        mode: 0644
    - copy:
        src: roles/certs/files/kubernetes.pem
        dest: /tmp
        owner: root
        group: root
        mode: 0644
    - copy:
        src: roles/certs/files/kubernetes-key.pem
        dest: /tmp
        owner: root
        group: root
        mode: 0644