- hosts: master
  become: true
  become_method: sudo
  roles:
    - kube_apiserver
    - kube_controller_manager
    - kube_scheduler
  tasks:
    - meta: flush_handlers
    - name: ensure kube-apiserver is running
      systemd: name=kube-apiserver state=started enabled=yes
    - name: ensure kube-controller-manager is running
      systemd: name=kube-controller-manager state=started enabled=yes
    - name: ensure kube-scheduler is running
      systemd: name=kube-scheduler state=started enabled=yes
    - name: Check master component
      command: kubectl get componentstatuses
      register: kubestatus
    - debug: var=kubestatus.stdout_lines