apiVersion: v1
kind: Pod
metadata:
  name: envbusy
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    env:
    # Use secret in real usage
    - name: SECRETFROMKUBE
      valueFrom:
        secretKeyRef:
          name: testsecret
          key: rahasiasaya
  restartPolicy: Always