apiVersion: v1
kind: Pod
metadata:
  name: filebusy
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
     - name: "test"
       mountPath: "/etc/secretgue"
       readOnly: true
  restartPolicy: Always
  volumes:
  - name: "test"
    secret:
      secretName: "testsecret"