- name: Download kube-proxy binary
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.6.4/bin/linux/amd64/kube-proxy
    dest: /usr/bin/kube-proxy

- name: Changing kube-proxy permission
  file: dest=/usr/bin/kube-proxy mode=a+x